# Generated by Django 3.0.5 on 2020-05-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0002_auto_20200505_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedition',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookedition',
            name='isbn',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
