# Generated by Django 3.0.5 on 2020-05-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0003_auto_20200507_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedition',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
